name: ip
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  animate_do: ^3.3.3
  better_player: ^0.0.83
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  flutter_staggered_animations: ^1.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  flutter_vlc_player: ^7.4.1
  font_awesome_flutter: ^10.7.0

  google_fonts: ^6.1.0
  intl: ^0.19.0
  line_icons: ^2.0.3
  lottie: ^3.1.0
  path_provider: ^2.1.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animation/
    - assets/icons/
